#!/usr/bin/env python3
import sys
import dbus, dbus.exceptions
import argparse


class MyParser(argparse.ArgumentParser):
    def error(self, message):
        sys.stderr.write('error: %s\n' % message)
        self.print_help()
        sys.exit(2)

if __name__ == "__main__":
    CONTROLLER_MODES = ['powersave', 'normal', 'performance']

    try:
        bus = dbus.SystemBus()
        gpu_manager = bus.get_object("ee.ounapuu.GPUManager", "/ee/ounapuu/GPUManager")
    except dbus.exceptions.DBusException as e:
        print("Failed to initialize D-Bus object: '%s'" % str(e))
        sys.exit(2)

    parser = MyParser(argparse.ArgumentParser())
    parser.add_argument("mode", help="Starts the GPU Manager Service in a given mode. Available modes: powersave, normal, performance",
                        type=str, nargs='?', default='normal')
    args = parser.parse_args()
    if args.mode in CONTROLLER_MODES:
        gpu_manager.set_mode(args.mode)
    else:
        # print("Invalid argument ", args.action)
        parser.error("Invalid argument " + str(args.action))
